language: generic

sudo: required

services:
    - docker

script:
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash .travis-build.sh $DOCKER_IMAGE

env:
    - DOCKER_IMAGE=centos:7
    - DOCKER_IMAGE=fedora:28
    - DOCKER_IMAGE=fedora:27
    - DOCKER_IMAGE=fedora:26

before_deploy:

deploy:
    skip_cleanup: true
    provider: script
    script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest /bin/sh -c "echo deploy done"
    on:
        branch: master
        condition: $DOCKER_IMAGE = centos:7
